### ISSUE TITLE
Pythonista 2.0 issues

### ISSUE THREAD

**Issue by Tkizzy** [TutorialDoctor/Pythonista-Projects#3]
A couple of the tutorials seem to be broken in 2.0. 

brightness_slider.py throws an IOerror

mydrafts.py seems to have the layout all messed up.

NavView Tutorial has an IO error can't find web view.pyui

**Comment by TutorialDoctor** [comment]
Thanks for commenting Tkizzy. Did you change the .json files to .pyui files? Later examples keep the .pyui files because I wasn't sure if they would download correctly.

**Comment by Tkizzy** [comment]
I was no aware I needed to change the files. Will give it a try...

**Comment by TutorialDoctor** [comment]
I went ahead and changed the .json files all back into .pyui files.
